package formularios;

import javax.swing.JPanel;

/**
 *
 * @author TELCOM MPC
 */
public class PaginasWeb extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioWebAFIP
     */
    public PaginasWeb() {
        initComponents();
    }

    public JPanel getJPanel() {
        return JPanel;
    }

    public void setJPanel(JPanel JPanel) {
        this.JPanel = JPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        cerrar = new javax.swing.JMenuItem();
        JPanel = new javax.swing.JPanel();

        cerrar.setText("Cerrar Ventana");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        popMenu.add(cerrar);

        setComponentPopupMenu(popMenu);

        JPanel.setComponentPopupMenu(popMenu);
        JPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPanelMouseClicked(evt);
            }
        });
        JPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                JPanelComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void JPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelMouseClicked

    }//GEN-LAST:event_JPanelMouseClicked

    private void JPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JPanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_JPanelComponentHidden

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JPopupMenu popMenu;
    // End of variables declaration//GEN-END:variables
}
